import time
time.sleep(2)
a = input("Reactant: ")
b = input("Reagent: ")
time.sleep(2)
print(f"Reacting {a} in presence of {b}", end="")
time.sleep(1)
print(".", end="")
time.sleep(1)
print(".", end="")
time.sleep(1)
print(".")
time.sleep(1.5)
print("100% 1-bromo-benzene")